name: Lint and Test Code

on:
  push:
    branches:
      - '*'  # Exécuter sur toutes les branches
  pull_request:
    branches:
      - '*'  # Exécuter pour toutes les pull requests

jobs:
  lint-and-test:
    name: Lint and Test Code
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-html pytest-cov

      # Étape 5 : Exécuter les tests avec couverture
      - name: Run Tests with Coverage
        run: |
          mkdir -p tests/rapport
          pytest --cov=app/lib --cov-report=html --html=tests/rapport/index.html

#++++